### ISSUE TITLE
🐞 [Bug] Split SSRF proxies fail on httpx 0.28 with TypeError on the removed proxies= argument

### ISSUE THREAD

**Issue by unbridled-41** [agentuniverse-ai/agentUniverse#3255]
### Version
master (commit `254ecd28`), package version 0.0.19, `httpx` 0.28.1 (`pyproject.toml` declares `httpx = ">=0.27.2"`)

### System
OS independent (the failure happens before any connection is opened). Reproduced on Linux/WSL2 with Python 3.12.3.

### Actions
Set the per-scheme SSRF proxy environment variables `SSRF_PROXY_HTTP_URL` and `SSRF_PROXY_HTTPS_URL`, then perform any request through `agentuniverse.agent.action.tool.utils.ssrf_proxy` — e.g. any `APITool` call.

### Problem
`make_request()` forwards the per-scheme proxy table to httpx as the `proxies=` argument, which httpx removed in 0.28 (deprecated in 0.26). Since `pyproject.toml` allows `httpx>=0.27.2` and commit `1f92d92a` deliberately widened that range to permit 0.28, a current install resolves to 0.28.x and this branch fails before a connection is attempted:

```
httpx: 0.28.1 | proxies: {'http://': 'http://127.0.0.1:8080', 'https://': 'http://127.0.0.1:8080'}
TypeError: request() got an unexpected keyword argument 'proxies'
```

The single-proxy branch (`SSRF_PROXY_ALL_URL`) already uses httpx's current `proxy=` argument and works, which is why only the split-proxy configuration is affected. The module is the only HTTP path of `APITool` (`api_tool.py:14` imports it, `api_tool.py:202` calls it), and `APITool` is what the product wires up for API/plugin tools (`agentuniverse_product/service/util/tool_util.py:70-75`).

### Expected
With `SSRF_PROXY_HTTP_URL`/`SSRF_PROXY_HTTPS_URL` set, requests are routed through those proxies and complete, on every httpx version the project declares support for. Requests must be proxied (not sent directly) when either configuration is set.

Acceptance: a regression test that routes a request through a real local HTTP proxy and asserts the request line arrives there (with a mocked `httpx.request` this class of failure is invisible), for both the split-proxy and the `SSRF_PROXY_ALL_URL` branches.

### reproduce
Run on unmodified master with httpx 0.28:

```python
import os
os.environ['SSRF_PROXY_HTTP_URL'] = 'http://127.0.0.1:8080'
os.environ['SSRF_PROXY_HTTPS_URL'] = 'http://127.0.0.1:8080'
import sys; sys.path.insert(0, '<repo root>')
import httpx
from agentuniverse.agent.action.tool.utils import ssrf_proxy

print(httpx.__version__)        # 0.28.1
print(ssrf_proxy.proxies)       # {'http://': 'http://127.0.0.1:8080', 'https://': 'http://127.0.0.1:8080'}
ssrf_proxy.get('http://example.com/')
# TypeError: request() got an unexpected keyword argument 'proxies'
# (raised from ssrf_proxy.py inside make_request, before any socket is opened)
```

Minimal form of the same incompatibility:

```
$ python -c "import httpx; httpx.request('GET','http://127.0.0.1:9/',proxies={'http://':'http://127.0.0.1:9'})"
TypeError: request() got an unexpected keyword argument 'proxies'
```

### Impact
For deployments that configure the per-scheme SSRF proxies, every request through `ssrf_proxy` — i.e. every `APITool`/plugin tool call — fails with a `TypeError` before any connection is made. Deployments using only `SSRF_PROXY_ALL_URL` or no proxy are unaffected.

### Location
`agentuniverse/agent/action/tool/utils/ssrf_proxy.py:21-27` (`make_request`).

### Related PR
Closes via #3249 — `fix(tool): use per-scheme httpx transports so split SSRF proxies work on httpx 0.28`.

### Duplicate check
Searched open and closed issues for `SSRF`, `SSRF_PROXY`, `ssrf_proxy`, `httpx`, `proxy`. No issue covers this module or the removed `proxies=` argument. The only open PR touching the area is #751, which adds a separate `HttpRequestTool` and does not modify `ssrf_proxy.py`. Note that the module's existing tests mock `httpx.request`, so this incompatibility is not caught by them; the environment variables are also not described anywhere under `docs/`.
